site_name: UQ PHYS3080/7080 Cosmology Project
nav:
    - Home: index.md
    - Instructions (download): CosmologyProject_2022.pdf
    - Theory (download): TheoryCosmo.pdf
    #- Statistics (download): StatisticsNotes.pdf
    - Code to get you started:
      - Basic cosmology: notebooks/CosmoIntro.ipynb
      - Calculating distances: notebooks/Distances.ipynb
      - Fitting supernova data: notebooks/Fit_Models.ipynb
      - (How we generated mock data): notebooks/Make_Mock_Data.ipynb
    - Data:
      - Data00: notebooks/data/Data00.txt
      - Data0: notebooks/data/Data0.txt
      - Data1: notebooks/data/Data1.txt
      - Data2: notebooks/data/Data2.txt
      - Data3: notebooks/data/Data3.txt
      - Data4: notebooks/data/Data4.txt
      - Data5: notebooks/data/Data5.txt
      - Data6: notebooks/data/Data6.txt
      - Data7: notebooks/data/Data7.txt

theme:
  name: "material"
repo_url: https://github.com/AstroUQ/PHYS3080_2022
plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: "numpy"
          rendering:
            show_source: false
      custom_templates: templates

# Commands:
# mkdocs serve (shows this page on a local server)
# mkdocs gh-deploy (deploys to sit)